apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
    labels:
        app.holos.run/cluster.name: workload
        app.holos.run/component.name: istio-gateway
        app.holos.run/project.name: network
        app.holos.run/team.name: platform
    name: network-istio-gateway
    namespace: argocd
spec:
    destination:
        server: https://kubernetes.default.svc
    project: network
    source:
        path: deploy/clusters/workload/projects/network/components/istio-gateway
        repoURL: https://github.com/jeffmccune/bank-of-holos.git
        targetRevision: main
