#! /bin/bash

# cd to the repository root
TOPLEVEL="$(cd $(dirname "$0") && git rev-parse --show-toplevel)"
cd "${TOPLEVEL}/examples/environments"

set -xeuo pipefail

## Bank Prod

apply() {
  local stack
  stack="$1"
  # Foundation
  kubectl apply --server-side=true -f deploy/clusters/workload/components/${stack}-bank-namespaces/${stack}-bank-namespaces.gen.yaml
  kubectl apply --server-side=true -f deploy/clusters/workload/components/${stack}-bank-projects/${stack}-bank-projects.gen.yaml
  # Secrets
  kubectl apply --server-side=true -f deploy/clusters/workload/components/${stack}-bank-secrets/${stack}-bank-secrets.gen.yaml
  kubectl wait --for=condition=complete job.batch/jwt-key-writer -n ${stack}-bank-security --timeout=300s
  # Bank Config
  kubectl apply --server-side=true -f deploy/clusters/workload/components/${stack}-bank-backend-config/${stack}-bank-backend-config.gen.yaml
  # Bank Databases
  kubectl apply --server-side=true -f deploy/clusters/workload/components/${stack}-bank-accounts-db/${stack}-bank-accounts-db.gen.yaml
  kubectl apply --server-side=true -f deploy/clusters/workload/components/${stack}-bank-ledger-db/${stack}-bank-ledger-db.gen.yaml
  # Bank Backend Services
  kubectl apply --server-side=true -f deploy/clusters/workload/components/${stack}-bank-contacts/${stack}-bank-contacts.gen.yaml
  kubectl apply --server-side=true -f deploy/clusters/workload/components/${stack}-bank-balance-reader/${stack}-bank-balance-reader.gen.yaml
  kubectl apply --server-side=true -f deploy/clusters/workload/components/${stack}-bank-userservice/${stack}-bank-userservice.gen.yaml
  kubectl apply --server-side=true -f deploy/clusters/workload/components/${stack}-bank-ledger-writer/${stack}-bank-ledger-writer.gen.yaml
  kubectl apply --server-side=true -f deploy/clusters/workload/components/${stack}-bank-transaction-history/${stack}-bank-transaction-history.gen.yaml
  # Bank Frontend
  kubectl apply --server-side=true -f deploy/clusters/workload/components/${stack}-bank-frontend/${stack}-bank-frontend.gen.yaml
  # Routes
  kubectl apply --server-side=true -f deploy/clusters/workload/components/${stack}-bank-routes/${stack}-bank-routes.gen.yaml
}

apply dev
# apply test
# apply stage
apply prod


exit 0
