#! /bin/bash

# cd to the repository root
TOPLEVEL="$(cd $(dirname "$0") && git rev-parse --show-toplevel)"
cd "${TOPLEVEL}/examples/environments"

set -xeuo pipefail

export NO_WAIT=1

./scripts/apply-stack prod
./scripts/apply-stack dev
./scripts/apply-stack sandbox-jeff

exit 0
