apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
    labels:
        app.holos.run/cluster.name: management
        app.holos.run/component.name: private-chart
        app.holos.run/project.name: holos
        app.holos.run/team.name: holos-authors
    name: holos-private-chart
    namespace: argocd
spec:
    destination:
        server: https://kubernetes.default.svc
    project: holos
    source:
        path: deploy/clusters/management/projects/holos/components/private-chart
        repoURL: https://github.com/holos-run/bank-of-holos.git
        targetRevision: main
