apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.holos.run/cluster.name: workload
    app.holos.run/component.name: test-bank-backend-config
    app.holos.run/environment.name: test
    app.holos.run/project.name: nonprod-bank-backend
    app.holos.run/stack.name: bank-of-holos
    app.holos.run/team.name: backend
    application: bank-of-holos
    argocd.argoproj.io/instance: nonprod-bank-backend-test-bank-backend-config
    environment: test
    tier: backend
  name: bank-of-holos
  namespace: test-bank-backend
---
apiVersion: v1
data:
  DEMO_LOGIN_PASSWORD: bankofanthos
  DEMO_LOGIN_USERNAME: testuser
  USE_DEMO_DATA: "True"
kind: ConfigMap
metadata:
  labels:
    app.holos.run/cluster.name: workload
    app.holos.run/component.name: test-bank-backend-config
    app.holos.run/environment.name: test
    app.holos.run/project.name: nonprod-bank-backend
    app.holos.run/stack.name: bank-of-holos
    app.holos.run/team.name: backend
    application: bank-of-holos
    argocd.argoproj.io/instance: nonprod-bank-backend-test-bank-backend-config
    environment: test
    tier: backend
  name: demo-data-config
  namespace: test-bank-backend
---
apiVersion: v1
data:
  LOCAL_ROUTING_NUM: "883745000"
  PUB_KEY_PATH: /tmp/.ssh/publickey
kind: ConfigMap
metadata:
  labels:
    app.holos.run/cluster.name: workload
    app.holos.run/component.name: test-bank-backend-config
    app.holos.run/environment.name: test
    app.holos.run/project.name: nonprod-bank-backend
    app.holos.run/stack.name: bank-of-holos
    app.holos.run/team.name: backend
    application: bank-of-holos
    argocd.argoproj.io/instance: nonprod-bank-backend-test-bank-backend-config
    environment: test
    tier: backend
  name: environment-config
  namespace: test-bank-backend
---
apiVersion: v1
data:
  BALANCES_API_ADDR: balancereader.test-bank-backend.svc:8080
  CONTACTS_API_ADDR: contacts.test-bank-backend.svc:8080
  HISTORY_API_ADDR: transactionhistory.test-bank-backend.svc:8080
  TRANSACTIONS_API_ADDR: ledgerwriter.test-bank-backend.svc:8080
  USERSERVICE_API_ADDR: userservice.test-bank-backend.svc:8080
kind: ConfigMap
metadata:
  labels:
    app.holos.run/cluster.name: workload
    app.holos.run/component.name: test-bank-backend-config
    app.holos.run/environment.name: test
    app.holos.run/project.name: nonprod-bank-backend
    app.holos.run/stack.name: bank-of-holos
    app.holos.run/team.name: backend
    application: bank-of-holos
    argocd.argoproj.io/instance: nonprod-bank-backend-test-bank-backend-config
    environment: test
    tier: backend
  name: service-api-config
  namespace: test-bank-backend
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  labels:
    app.holos.run/cluster.name: workload
    app.holos.run/component.name: test-bank-backend-config
    app.holos.run/environment.name: test
    app.holos.run/project.name: nonprod-bank-backend
    app.holos.run/stack.name: bank-of-holos
    app.holos.run/team.name: backend
    application: bank-of-holos
    argocd.argoproj.io/instance: nonprod-bank-backend-test-bank-backend-config
    environment: test
    tier: backend
  name: jwt-key
  namespace: test-bank-backend
spec:
  dataFrom:
  - extract:
      key: jwt-key
  refreshInterval: 5s
  secretStoreRef:
    kind: SecretStore
    name: test-bank-security
  target:
    name: jwt-key
---
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  labels:
    app.holos.run/cluster.name: workload
    app.holos.run/component.name: test-bank-backend-config
    app.holos.run/environment.name: test
    app.holos.run/project.name: nonprod-bank-backend
    app.holos.run/stack.name: bank-of-holos
    app.holos.run/team.name: backend
    application: bank-of-holos
    argocd.argoproj.io/instance: nonprod-bank-backend-test-bank-backend-config
    environment: test
    tier: backend
  name: test-bank-security
  namespace: test-bank-backend
spec:
  provider:
    kubernetes:
      auth:
        serviceAccount:
          name: bank-of-holos
      remoteNamespace: test-bank-security
      server:
        caProvider:
          key: ca.crt
          name: kube-root-ca.crt
          type: ConfigMap
        url: https://kubernetes.default.svc
---
apiVersion: gateway.networking.k8s.io/v1beta1
kind: ReferenceGrant
metadata:
  labels:
    app.holos.run/cluster.name: workload
    app.holos.run/component.name: test-bank-backend-config
    app.holos.run/environment.name: test
    app.holos.run/project.name: nonprod-bank-backend
    app.holos.run/stack.name: bank-of-holos
    app.holos.run/team.name: backend
    application: bank-of-holos
    argocd.argoproj.io/instance: nonprod-bank-backend-test-bank-backend-config
    environment: test
    tier: backend
  name: istio-ingress
  namespace: test-bank-backend
spec:
  from:
  - group: gateway.networking.k8s.io
    kind: HTTPRoute
    namespace: istio-ingress
  to:
  - group: ""
    kind: Service
