apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
    labels:
        app.holos.run/cluster.name: management
        app.holos.run/component.name: external-secrets
        app.holos.run/project.name: security
        app.holos.run/team.name: security
    name: security-external-secrets
    namespace: argocd
spec:
    destination:
        server: https://kubernetes.default.svc
    project: security
    source:
        path: deploy/clusters/management/projects/security/components/external-secrets
        repoURL: https://github.com/jeffmccune/bank-of-holos.git
        targetRevision: main
