#! /bin/bash
#
# Generate a secret to replace the insecure accounts-db-config ConfigMap
# https://github.com/GoogleCloudPlatform/bank-of-anthos/blob/v0.6.5/kubernetes-manifests/ledger-db.yaml#L17-L22

tmpdir="$(mktemp -d)"
finish() {
  status=$?
  rm -rf "${tmpdir}"
  return $status
}
trap finish EXIT

set -euo pipefail

cd "$tmpdir"
mkdir secret
cd secret

export LC_ALL=C

POSTGRES_DB="postgresdb"
POSTGRES_USER="admin"
set +o pipefail
POSTGRES_PASSWORD="$(tr -dc A-Za-z0-9 </dev/urandom | head -c 20)"
set -o pipefail

SPRING_DATASOURCE_PASSWORD="${POSTGRES_PASSWORD}"
SPRING_DATASOURCE_URL="jdbc:postgresql://ledger-db:5432/${POSTGRES_DB}"
SPRING_DATASOURCE_USERNAME="${POSTGRES_USER}"

echo -n "$POSTGRES_DB" > POSTGRES_DB
echo -n "$POSTGRES_USER" > POSTGRES_USER
echo -n "$POSTGRES_PASSWORD" > POSTGRES_PASSWORD
echo -n "$SPRING_DATASOURCE_PASSWORD" > SPRING_DATASOURCE_PASSWORD
echo -n "$SPRING_DATASOURCE_URL" > SPRING_DATASOURCE_URL
echo -n "$SPRING_DATASOURCE_USERNAME" > SPRING_DATASOURCE_USERNAME

cd ..

echo "copying secret into kubernetes manifest secret.yaml" >&2
kubectl create secret generic ledger-db-config --from-file=secret --dry-run=client -o yaml > secret.yaml

echo "applying secret.yaml" >&2
kubectl apply --server-side=true -f secret.yaml

echo "cleaning up" >&2
rm -rf secret secret.yaml

echo "ok done" >&2
