apiVersion: v1
kind: Namespace
metadata:
  labels:
    app.holos.run/cluster.name: management
    app.holos.run/component.name: namespaces
    app.holos.run/project.name: holos
    app.holos.run/team.name: holos-authors
    argocd.argoproj.io/instance: holos-namespaces
    kubernetes.io/metadata.name: holos
  name: holos
