apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
    labels:
        app.holos.run/cluster.name: management
        app.holos.run/component.name: accounts-db
        app.holos.run/environment.name: test
        app.holos.run/project.name: test-bank-backend
        app.holos.run/stack.name: bank-of-holos
        app.holos.run/team.name: backend
    name: test-bank-backend-accounts-db
    namespace: argocd
spec:
    destination:
        server: https://kubernetes.default.svc
    project: test-bank-backend
    source:
        path: deploy/clusters/management/projects/test-bank-backend/components/accounts-db
        repoURL: https://github.com/jeffmccune/bank-of-holos.git
        targetRevision: main
