apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
    labels:
        app.holos.run/cluster.name: workload
        app.holos.run/component.name: prod-east-podinfo
        app.holos.run/environment.name: prod-east
        app.holos.run/project.name: prod-bank-web
        app.holos.run/stack.name: bank-of-holos
        app.holos.run/team.name: frontend
    name: prod-bank-web-prod-east-podinfo
    namespace: argocd
spec:
    destination:
        server: https://kubernetes.default.svc
    project: prod-bank-web
    source:
        path: deploy/clusters/workload/projects/prod-bank-web/components/prod-east-podinfo
        repoURL: https://github.com/holos-run/bank-of-holos.git
        targetRevision: main
