apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
    labels:
        app.holos.run/cluster.name: workload
        app.holos.run/component.name: chart-museum
        app.holos.run/project.name: holos
        app.holos.run/team.name: holos-authors
    name: holos-chart-museum
    namespace: argocd
spec:
    destination:
        server: https://kubernetes.default.svc
    project: holos
    source:
        path: deploy/clusters/workload/projects/holos/components/chart-museum
        repoURL: https://github.com/holos-run/bank-of-holos.git
        targetRevision: main
