apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.holos.run/cluster.name: workload
    app.holos.run/component.name: prod-west-frontend
    app.holos.run/environment.name: prod-west
    app.holos.run/project.name: prod-bank-web
    app.holos.run/stack.name: bank-of-holos
    app.holos.run/team.name: frontend
    argocd.argoproj.io/instance: prod-bank-web-prod-west-frontend
  name: bank-of-holos
  namespace: prod-west-bank-frontend
---
apiVersion: v1
data:
  DEMO_LOGIN_PASSWORD: bankofanthos
  DEMO_LOGIN_USERNAME: testuser
  USE_DEMO_DATA: "True"
kind: ConfigMap
metadata:
  labels:
    app.holos.run/cluster.name: workload
    app.holos.run/component.name: prod-west-frontend
    app.holos.run/environment.name: prod-west
    app.holos.run/project.name: prod-bank-web
    app.holos.run/stack.name: bank-of-holos
    app.holos.run/team.name: frontend
    argocd.argoproj.io/instance: prod-bank-web-prod-west-frontend
  name: demo-data-config
  namespace: prod-west-bank-frontend
---
apiVersion: v1
data:
  LOCAL_ROUTING_NUM: "883745000"
  PUB_KEY_PATH: /tmp/.ssh/publickey
kind: ConfigMap
metadata:
  labels:
    app.holos.run/cluster.name: workload
    app.holos.run/component.name: prod-west-frontend
    app.holos.run/environment.name: prod-west
    app.holos.run/project.name: prod-bank-web
    app.holos.run/stack.name: bank-of-holos
    app.holos.run/team.name: frontend
    argocd.argoproj.io/instance: prod-bank-web-prod-west-frontend
  name: environment-config
  namespace: prod-west-bank-frontend
---
apiVersion: v1
data:
  BALANCES_API_ADDR: balancereader.prod-west-bank-backend.svc:8080
  CONTACTS_API_ADDR: contacts.prod-west-bank-backend.svc:8080
  HISTORY_API_ADDR: transactionhistory.prod-west-bank-backend.svc:8080
  TRANSACTIONS_API_ADDR: ledgerwriter.prod-west-bank-backend.svc:8080
  USERSERVICE_API_ADDR: userservice.prod-west-bank-backend.svc:8080
kind: ConfigMap
metadata:
  labels:
    app.holos.run/cluster.name: workload
    app.holos.run/component.name: prod-west-frontend
    app.holos.run/environment.name: prod-west
    app.holos.run/project.name: prod-bank-web
    app.holos.run/stack.name: bank-of-holos
    app.holos.run/team.name: frontend
    argocd.argoproj.io/instance: prod-bank-web-prod-west-frontend
  name: service-api-config
  namespace: prod-west-bank-frontend
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.holos.run/cluster.name: workload
    app.holos.run/component.name: prod-west-frontend
    app.holos.run/environment.name: prod-west
    app.holos.run/project.name: prod-bank-web
    app.holos.run/stack.name: bank-of-holos
    app.holos.run/team.name: frontend
    application: bank-of-holos
    argocd.argoproj.io/instance: prod-bank-web-prod-west-frontend
    environment: prod-west
    team: frontend
    tier: web
  name: frontend
  namespace: prod-west-bank-frontend
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: frontend
    application: bank-of-holos
    environment: prod-west
    tier: web
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.holos.run/cluster.name: workload
    app.holos.run/component.name: prod-west-frontend
    app.holos.run/environment.name: prod-west
    app.holos.run/project.name: prod-bank-web
    app.holos.run/stack.name: bank-of-holos
    app.holos.run/team.name: frontend
    application: bank-of-holos
    argocd.argoproj.io/instance: prod-bank-web-prod-west-frontend
    environment: prod-west
    team: frontend
    tier: web
  name: frontend
  namespace: prod-west-bank-frontend
spec:
  selector:
    matchLabels:
      app: frontend
      application: bank-of-holos
      environment: prod-west
  template:
    metadata:
      labels:
        app: frontend
        application: bank-of-holos
        environment: prod-west
        team: frontend
        tier: web
    spec:
      containers:
      - env:
        - name: BANK_NAME
          value: Bank of Holos
        - name: ENV_PLATFORM
          value: local
        - name: VERSION
          value: v0.6.5
        - name: PORT
          value: "8080"
        - name: ENABLE_TRACING
          value: "false"
        - name: SCHEME
          value: https
        - name: LOG_LEVEL
          value: info
        - name: DEFAULT_USERNAME
          valueFrom:
            configMapKeyRef:
              key: DEMO_LOGIN_USERNAME
              name: demo-data-config
        - name: DEFAULT_PASSWORD
          valueFrom:
            configMapKeyRef:
              key: DEMO_LOGIN_PASSWORD
              name: demo-data-config
        - name: REGISTERED_OAUTH_CLIENT_ID
          valueFrom:
            configMapKeyRef:
              key: DEMO_OAUTH_CLIENT_ID
              name: oauth-config
              optional: true
        - name: ALLOWED_OAUTH_REDIRECT_URI
          valueFrom:
            configMapKeyRef:
              key: DEMO_OAUTH_REDIRECT_URI
              name: oauth-config
              optional: true
        envFrom:
        - configMapRef:
            name: environment-config
        - configMapRef:
            name: service-api-config
        image: us-central1-docker.pkg.dev/bank-of-anthos-ci/bank-of-anthos/frontend:v0.6.5@sha256:d72050f70d12383e4434ad04d189b681dc625f696087ddf0b5df641645c9dafa
        livenessProbe:
          httpGet:
            path: /ready
            port: 8080
          initialDelaySeconds: 60
          periodSeconds: 15
          timeoutSeconds: 30
        name: front
        readinessProbe:
          httpGet:
            path: /ready
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 5
          timeoutSeconds: 10
        resources:
          limits:
            cpu: 250m
            memory: 128Mi
          requests:
            cpu: 100m
            memory: 64Mi
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - all
          privileged: false
          readOnlyRootFilesystem: true
        volumeMounts:
        - mountPath: /tmp
          name: tmp
        - mountPath: /tmp/.ssh
          name: publickey
          readOnly: true
      securityContext:
        fsGroup: 1000
        runAsGroup: 1000
        runAsNonRoot: true
        runAsUser: 1000
        seccompProfile:
          type: RuntimeDefault
      serviceAccountName: bank-of-holos
      terminationGracePeriodSeconds: 5
      volumes:
      - emptyDir: {}
        name: tmp
      - name: publickey
        secret:
          items:
          - key: jwtRS256.key.pub
            path: publickey
          secretName: jwt-key
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  labels:
    app.holos.run/cluster.name: workload
    app.holos.run/component.name: prod-west-frontend
    app.holos.run/environment.name: prod-west
    app.holos.run/project.name: prod-bank-web
    app.holos.run/stack.name: bank-of-holos
    app.holos.run/team.name: frontend
    argocd.argoproj.io/instance: prod-bank-web-prod-west-frontend
  name: jwt-key
  namespace: prod-west-bank-frontend
spec:
  dataFrom:
  - extract:
      key: jwt-key
  refreshInterval: 5s
  secretStoreRef:
    kind: SecretStore
    name: prod-west-bank-security
  target:
    name: jwt-key
---
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  labels:
    app.holos.run/cluster.name: workload
    app.holos.run/component.name: prod-west-frontend
    app.holos.run/environment.name: prod-west
    app.holos.run/project.name: prod-bank-web
    app.holos.run/stack.name: bank-of-holos
    app.holos.run/team.name: frontend
    argocd.argoproj.io/instance: prod-bank-web-prod-west-frontend
  name: prod-west-bank-security
  namespace: prod-west-bank-frontend
spec:
  provider:
    kubernetes:
      auth:
        serviceAccount:
          name: bank-of-holos
      remoteNamespace: prod-west-bank-security
      server:
        caProvider:
          key: ca.crt
          name: kube-root-ca.crt
          type: ConfigMap
        url: https://kubernetes.default.svc
---
apiVersion: gateway.networking.k8s.io/v1beta1
kind: ReferenceGrant
metadata:
  labels:
    app.holos.run/cluster.name: workload
    app.holos.run/component.name: prod-west-frontend
    app.holos.run/environment.name: prod-west
    app.holos.run/project.name: prod-bank-web
    app.holos.run/stack.name: bank-of-holos
    app.holos.run/team.name: frontend
    argocd.argoproj.io/instance: prod-bank-web-prod-west-frontend
  name: istio-ingress
  namespace: prod-west-bank-frontend
spec:
  from:
  - group: gateway.networking.k8s.io
    kind: HTTPRoute
    namespace: istio-ingress
  to:
  - group: ""
    kind: Service
