apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
    labels:
        app.holos.run/cluster.name: workload
        app.holos.run/component.name: test-podinfo
        app.holos.run/environment.name: test
        app.holos.run/project.name: nonprod-bank-web
        app.holos.run/stack.name: bank-of-holos
        app.holos.run/team.name: frontend
    name: nonprod-bank-web-test-podinfo
    namespace: argocd
spec:
    destination:
        server: https://kubernetes.default.svc
    project: nonprod-bank-web
    source:
        path: deploy/clusters/workload/projects/nonprod-bank-web/components/test-podinfo
        repoURL: https://github.com/holos-run/bank-of-holos.git
        targetRevision: main
